default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 12 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  primary:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    pool: 20

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    pool: 5

  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    pool: 5


